# Generated by Django 5.2.8 on 2026-01-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='في الانتظار', max_length=50),
        ),
    ]
