# Generated by Django 5.2.8 on 2026-01-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_customuser_address_customuser_location_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='secure_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
