# Generated by Django 5.2.8 on 2026-02-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergroup',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب الإلغاء'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=10, verbose_name='الكمية المتاحة'),
        ),
    ]
