# Generated by Django 5.2.8 on 2026-02-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
