# Generated by Django 5.2.8 on 2026-03-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_ordergroup_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
